# version: 2.1

# orbs:
#   go: circleci/go@3.0.4

# jobs:
#   build_and_test: 
#     executor:
#       name: go/default 
#       tag: '1.22' 
#     steps:
#       - checkout 
#       - go/mod-download 
#       - go/test: 
#           covermode: atomic
#           failfast: true
#           race: true
#       - persist_to_workspace:
#           root: .
#           paths: 
#             - .

# workflows:
#   build_test:
#     jobs:
#       - build_and_test

version: 2.1


jobs:
  build_and_test: 
    docker:
      - image: cimg/go:1.22

    resource_class: axfnqfpxkjrgg5mrbkqosw/eks-runner

    steps:
      - checkout 
      
      - run:
          name: "Download Go Modules"
          command: go mod download
          
      - run:
          name: "Run Tests"
          command: go test -v -covermode=atomic -failfast -race ./...
          
      - persist_to_workspace:
          root: .
          paths: 
            - .

workflows:
  build_test:
    jobs:
      - build_and_test

